import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import {AppBar, BottomNavigation, Toolbar} from '@mui/material'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  Restore as RestoreIcon,
  Favorite as FavoriteIcon,
  LocationOn as LocationOnIcon
} from '@mui/icons-material';
import AppThemeProvider from "@/core/providers/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppThemeProvider>
          <AppRouterCacheProvider>
            <AppBar position="static">
              <Toolbar>
                <div>AppBar - Toolbar</div>
              </Toolbar>
            </AppBar>
            {children}
            <BottomNavigation />
          </AppRouterCacheProvider>
        </AppThemeProvider>
      </body>
    </html>
  );
}
